import { IsBoolean, IsOptional, IsString, MaxLength, MinLength } from 'class-validator';

export class RegisterDeviceDto {
  /**
   * Opaque per-installation identifier generated by the app and kept in secure
   * storage. Not a hardware id: those are restricted on both platforms and
   * would make the record more identifying than it needs to be.
   */
  @IsString()
  @MinLength(16)
  @MaxLength(191)
  fingerprint!: string;

  @IsOptional()
  @IsString()
  @MaxLength(120)
  name?: string;

  @IsOptional()
  @IsString()
  @MaxLength(64)
  platform?: string;

  @IsOptional()
  @IsString()
  @MaxLength(32)
  appVersion?: string;

  /** Expo push token. Absent when permission has not been granted, which is not
      an error — the device is still registered, just not reachable by push. */
  @IsOptional()
  @IsString()
  @MaxLength(255)
  pushToken?: string;

  /** Set when the user declined the permission prompt, so the app can avoid
      asking again on every login. */
  @IsOptional()
  @IsBoolean()
  pushPermissionDeclined?: boolean;
}
